# Generated by Django 4.2.15 on 2024-08-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
