# Generated by Django 4.2.15 on 2024-08-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.BigIntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
